<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-03T13:12:33 IST" name="Surefire suite" finished-at="2024-12-03T13:12:42 IST" duration-ms="8808">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:cucumber.TestNGTestRunner@41e36e46]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2024-12-03T13:12:33 IST" name="Surefire test" finished-at="2024-12-03T13:12:42 IST" duration-ms="8808">
      <class name="cucumber.TestNGTestRunner">
        <test-method is-config="true" signature="setUpClass(org.testng.ITestContext)[pri:0, instance:cucumber.TestNGTestRunner@41e36e46]" started-at="2024-12-03T13:12:33 IST" name="setUpClass" finished-at="2024-12-03T13:12:34 IST" duration-ms="842" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@1bc0d349]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:cucumber.TestNGTestRunner@41e36e46]" started-at="2024-12-03T13:12:34 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-12-03T13:12:42 IST" duration-ms="7852" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Incorrect username and password"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Error validation by Cucumber"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login Successfully] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login Successfully] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at shankarnrraibagi.stepDefinition.StepDefinitionImpl.error_message_is_displayed(StepDefinitionImpl.java:63)
at âœ½."Incorrect email or password." message is displayed(file:///C:/Users/DELL/Desktop/Programs/SeleniumFrameworkDesign/src/test/java/cucumber/ErrorValidation.feature:10)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:cucumber.TestNGTestRunner@41e36e46]" started-at="2024-12-03T13:12:42 IST" name="tearDownClass" finished-at="2024-12-03T13:12:42 IST" duration-ms="40" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- cucumber.TestNGTestRunner -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
